version: '3.8'

services:
  xdbcexpt:
    image: xdbc-expt
    build:
      context: .  
      dockerfile: Dockerfile  # Path relative to context
    container_name: xdbcexpt
    volumes:
      # - ./experiments_new/res:/app/experiments_new/res  # Only mount results
      # - ./experiments_new/res/xdbc_plans:/app/experiments_new/res/xdbc_plans  # Mount xdbc_plans specifically
      # - ./experiments_new/res/pdf_plots:/app/experiments_new/res/pdf_plots  # Mount xdbc_plans specifically
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
      - /dev/shm:/dev/shm
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    tty: true
    stdin_open: true
    network_mode: host
