CREATE TABLE IF NOT EXISTS iotm
(
    id             integer,
    flowid         character varying(45),
    srcip          character varying(16),
    srcport        integer,
    dstip          character varying(16),
    dstport        integer,
    protocol       integer,
    "timestamp"    character varying(23),
    flowduration   integer,
    totfwdpkts     integer,
    totbwdpkts     integer,
    totlenfwdpkts  double precision,
    totlenbwdpkts  double precision,
    fwdpktlenmax   double precision,
    fwdpktlenmin   double precision,
    fwdpktlenmean  double precision,
    fwdpktlenstd   double precision,
    bwdpktlenmax   double precision,
    bwdpktlenmin   double precision,
    bwdpktlenmean  double precision,
    bwdpktlenstd   double precision,
    flowbytspers   double precision,
    flowpktspers   double precision,
    flowiatmean    double precision,
    flowiatstd     double precision,
    flowiatmax     double precision,
    flowiatmin     double precision,
    fwdiattot      double precision,
    fwdiatmean     double precision,
    fwdiatstd      double precision,
    fwdiatmax      double precision,
    fwdiatmin      double precision,
    bwdiattot      double precision,
    bwdiatmean     double precision,
    bwdiatstd      double precision,
    bwdiatmax      double precision,
    bwdiatmin      double precision,
    fwdpshflags    integer,
    bwdpshflags    integer,
    fwdurgflags    integer,
    bwdurgflags    integer,
    fwdheaderlen   integer,
    bwdheaderlen   integer,
    fwdpktspers    double precision,
    bwdpktspers    double precision,
    pktlenmin      double precision,
    pktlenmax      double precision,
    pktlenmean     double precision,
    pktlenstd      double precision,
    pktlenvar      double precision,
    finflagcnt     integer,
    synflagcnt     integer,
    rstflagcnt     integer,
    pshflagcnt     integer,
    ackflagcnt     integer,
    urgflagcnt     integer,
    cweflagcount   integer,
    eceflagcnt     integer,
    downperupratio double precision,
    pktsizeavg     double precision,
    fwdsegsizeavg  double precision,
    bwdsegsizeavg  double precision,
    fwdbytsperbavg integer,
    fwdpktsperbavg integer,
    fwdblkrateavg  integer,
    bwdbytsperbavg integer,
    bwdpktsperbavg integer,
    bwdblkrateavg  integer,
    subflowfwdpkts integer,
    subflowfwdbyts integer,
    subflowbwdpkts integer,
    subflowbwdbyts integer,
    initfwdwinbyts integer,
    initbwdwinbyts integer,
    fwdactdatapkts integer,
    fwdsegsizemin  integer,
    activemean     integer,
    activestd      integer,
    activemax      integer,
    activemin      integer,
    idlemean       double precision,
    idlestd        double precision,
    idlemax        double precision,
    idlemin        double precision,
    label          character varying(9)
);